version: 2
sources:
  - name: warehouse
    database: data-warehouse-475122
    schema: warehouse
    tables:
      - name: card_transactions
        loaded_at_field: _airbyte_extracted_at
      - name: exercise_log
        loaded_at_field: _airbyte_extracted_at
      - name: recipe_log
        loaded_at_field: _airbyte_extracted_at
      - name: shopping_log
        loaded_at_field: _airbyte_extracted_at
      - name: users
        loaded_at_field: _airbyte_extracted_at
      - name: weights
        loaded_at_field: _airbyte_extracted_at
      - name: merchants
        loaded_at_field: _airbyte_extracted_at
      - name: merchant_account_map
        loaded_at_field: _airbyte_extracted_at
      - name: merchant_regex
        loaded_at_field: _airbyte_extracted_at
      - name: accounts_leaf
        loaded_at_field: _airbyte_extracted_at
      - name: transaction_merchant_map
        loaded_at_field: _airbyte_extracted_at
      - name: subcategories
        loaded_at_field: _airbyte_extracted_at
      - name: categories
        loaded_at_field: _airbyte_extracted_at