version: 2
sources:
  - name: warehouse
    database: data-warehouse-475122
    schema: warehouse
    tables:
      - name: card_transactions
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: exercise_log
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: exercises
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: exercise_muscles
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: exercise_loads
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: recipe_log
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: shopping_log
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: users
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: weights
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: merchants
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: transaction_merchant_maps
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: subcategories
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: categories
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: blog_posts
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: channels
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: email_settings
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: priorities
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: youtube_categories
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: videos
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: video_transcripts
        config:
          loaded_at_field: _airbyte_extracted_at
  - name: github
    database: data-warehouse-475122
    schema: github
    tables:
      - name: branches
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: commits
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: repositories
        config:
          loaded_at_field: _airbyte_extracted_at
      - name: users
        config:
          loaded_at_field: _airbyte_extracted_at